defaults:
  - _self_

autoencoder:
  type: "masked"
  input_dim: 201640
  latent_dim: 16
  hidden_layers: [256, 128, 64]
  activation: "ReLU"
  dropout_rate: 0.2

name: "lstm" # This acts as a default if model.name is not in conf/config.yaml
             # and is part of what _self_ merges.